# .github/workflows/deploy.yml
name: Deploy Hugo site to GitHub Pages

on:
  push:
    branches:
      - main  # hoặc "master" nếu bạn dùng branch này

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: true  # nếu dùng theme dưới dạng git submodule

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.126.1' # hoặc bản mới nhất

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
